name: Upload Release Asset

on:
  release:
    types:
      - released

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    outputs:
      tgz_file: ${{ steps.build.outputs.file }}
    steps:
      - uses: actions/checkout@v3
      - uses: coursier/cache-action@v6.3
      - uses: VirtusLab/scala-cli-setup@v0.1
        with:
          jvm: "11"
      - name: Build project
        id: build
        env:
          TAG : ${{ github.event.release.tag_name }}
        run: |
          scala-cli package . -o scala-works-cli
          tar -czvf scala-works-cli-$TAG-ubuntu-latest.tar.gz scala-works-cli
          echo "file=scala-works-cli-$TAG-ubuntu-latest.tar.gz" >> $GITHUB_OUTPUT
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./${{ steps.build.outputs.file }}
          asset_name: ${{ steps.build.outputs.file }}
          asset_content_type: application/gzip